---
- hosts: all
  gather_facts: no
  tasks:
  - name: Wait 600 seconds for target connection to become reachable/usable
    wait_for_connection:
      delay: 20
      timeout: 300

  - name: now gather facts
    setup:

  - name: Update and upgrade packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 3600

  - name: Install prerequisites for Docker repository
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common', 'python3-pip']
      update_cache: yes

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

  - name: Install Docker CE
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      update_cache: yes
      
  - name: Start docker service
    service:
      name: docker
      state: started

  - name: Add ubuntu user to docker group
    ansible.builtin.user:
      name: ubuntu
      group: ubuntu
      groups: docker
      append: yes

  - name: Install bottle python package
    pip:
      name: docker
      
  - name: Create  container
    docker_container:
      name: webapp
      image: "pidu2/webapp_test:{{ webapp_test_version }}"
      state: started
      ports:
        - "443:443"
        - "80:80"
